version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID >> .env
      - npm install
      - npm run generate
  pre_build:
    commands:
      - aws s3 rm --recursive s3://$S3_BUCKET_WEBPAGE
      - aws s3 cp ./dist s3://$S3_BUCKET_WEBPAGE --recursive
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
